### ISSUE TITLE
iOS 8 : Add support for layout margins

### ISSUE THREAD

**Issue by guillaume-algis** [Masonry/Masonry#108]
While it does seems to be documented anywhere by Apple, [iOS 8 introduced a couple of new layout attributes](http://ericasadun.com/2014/08/28/auto-layout-ios-8/) in NSLayoutConstraint.h:

    NSLayoutAttributeLastBaseline = NSLayoutAttributeBaseline,
    NSLayoutAttributeFirstBaseline NS_ENUM_AVAILABLE_IOS(8_0),
    
    NSLayoutAttributeLeftMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeRightMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeTopMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeBottomMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeLeadingMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeTrailingMargin NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeCenterXWithinMargins NS_ENUM_AVAILABLE_IOS(8_0),
    NSLayoutAttributeCenterYWithinMargins NS_ENUM_AVAILABLE_IOS(8_0),

It would be nice to be able to use these using Masonry. Something like:

    [view1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(superview.mas_leftMargin);
    }];

**Comment by CraigSiemens** [comment]
As far as I can tell, this issue has been closed but margins haven't been added yet. Is this being worked on or would a PR be welcome?

**Comment by cloudkite** [comment]
PRs are always welcome!

**Comment by fabb** [comment]
In the mean time this has been added: 1a7f0d235
