### ISSUE TITLE
How to update the Xib's Constraints

### ISSUE THREAD

**Issue by ZhipingYang** [Masonry/Masonry#120]
if i used code to creat a view and make it's constrains,it's works . but if i used by xib and update it's constrains ,the view's layout is very strange. when i creat view with code and add it's subviews which is creat by xib , finally the all views layout was perfect.

**Comment by matthewyan** [comment]
@ZhipingYang  请问具体是怎么操作的？谢谢

**Comment by matthewyan** [comment]
@leiyong316 我试了把xib的auto layout和size classes都禁用掉，也是ok的，不知道你描述的方法是什么样的？ 谢谢

**Comment by leiyong316** [comment]
@matthewyan  是在xib和storyboard里连接普通的view一样， 只不过声明的类型是NSLayoutConstraint,  在xib或storyboard里控件是你添加的约束

**Comment by ZhipingYang** [comment]
@matthewyan 已经知道怎么做了吗？

**Comment by matthewyan** [comment]
@ZhipingYang  我刚才试了一下

这样某个控件有很多约束，就要创建很多NSLayoutConstraint对象，这样是不是比较繁琐？

不知道我是否理解有误，谢谢

**Comment by leiyong316** [comment]
@matthewyan  没错， 就是约束多了后很繁琐。所以一般尽量在xib里把约束弄好。

**Comment by leiyong316** [comment]
@matthewyan   @ZhipingYang     我最近也遇到个问题， arc模式下内存只增不减. 运行一段时间后最终就会crash， 之前一直没在意。
比如 ： controllerA push 到 controllerB,  push后可能要在controllerB里做一些操作， 这时内存肯定会增加， 然后从controllerB pop 回controllerA时， 内存居然没减， 让我费解， 检查又无内存泄漏。 二位是否有高见？

**Comment by matthewyan** [comment]
@leiyong316 controllerB的dealloc有调用没？

**Comment by leiyong316** [comment]
@matthewyan  有呢

**Comment by ZhipingYang** [comment]
我现在基本上都不怎么用dealloc方法了。你有没有用instrument查看一下是那个地方的问题

**Comment by leiyong316** [comment]
使用instrument的leaks测了，没有泄漏， 是否还需要用别的模块测？

**Comment by ZhipingYang** [comment]
说一个课外话，你们是怎么用GitHub的paper？

**Comment by ZhipingYang** [comment]
@leon 具体那我也不是很清楚。不知道看看会不会block或者kvo其他什么造成的

**Comment by TheSolitary** [comment]
xib的约束都是NSLayoutConstraint，而masonry中mas_updateConstraints作用对象都是MASLayoutConstraint。
你可以尝试着修改一下源码也可以达到同样的效果，但是不知道会不会有其他问题，我正在尝试着询问作者。
```objc
 for (NSLayoutConstraint *existingConstraint in self.installedView.constraints.reverseObjectEnumerator) {
        //if (![existingConstraint isKindOfClass:MASLayoutConstraint.class]) continue;
        if (existingConstraint.firstItem != layoutConstraint.firstItem) continue;
        if (existingConstraint.secondItem != layoutConstraint.secondItem) continue;
        if (existingConstraint.firstAttribute != layoutConstraint.firstAttribute) continue;
        if (existingConstraint.secondAttribute != layoutConstraint.secondAttribute) continue;
        if (existingConstraint.relation != layoutConstraint.relation) continue;
        if (existingConstraint.multiplier != layoutConstraint.multiplier) continue;
        if (existingConstraint.priority != layoutConstraint.priority) continue;

        return (id)existingConstraint;
    }

**Comment by ZhipingYang** [comment]
@TheSolitary 你说的前提都是使用code添加约束，我现在还是比较习惯storyboard和xib，如果不是直接索引constraint，就要去遍历获取View的constraint，然后在修改？

**Comment by AugustRush** [comment]
用了xib拖拽添加约束，直接拖拽添加属性更新就好了，为什么要用masonry更新，真不明白

发自我的 iPhone

**Comment by TheSolitary** [comment]
@ZhipingYang 你应该是误会我的意思了，我贴出来的代码是修改过的，这样子完全不需要遍历或者索引constraint，直接可以用mas_updateConstraints来进行修改约束的。

**Comment by TheSolitary** [comment]
@AugustRush 如果你一个view中需要进行大量的动画，而且界面元素比较多，那你需要拖拽的属性岂不是太多了，维护也不方便。如果可以直接用masonry来更新的话，那么你应该可以很清晰的看到每个constraint。请原谅我有些强迫症。

**Comment by AugustRush** [comment]
这种情况应该分开写的，一个view上很多多控件，状态也不好管理，没有必须把所有控件都加到一个view上的理由吧

发自我的 iPhone
