### ISSUE TITLE
UITableViewCell contentView width issues when laying out subviews

### ISSUE THREAD

**Issue by slhodson969** [Masonry/Masonry#134]
Using Masonry to layout views in a `UITableViewCell` doesn't seem to work properly. It's as if the `contentView` isn't having a width set or something.

My code:
    
    self.addressLineOneLabel = [UILabel new];
    self.addressLineOneLabel.textAlignment = NSTextAlignmentCenter;

    [self.contentView addSubview:self.addressLineOneLabel];

    [self.addressLineOneLabel makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.contentView).with.offset(10);
        make.left.equalTo(self.contentView).with.offset(10);
        make.right.equalTo(self.contentView).with.offset(-10);
        make.bottom.equalTo(self.contentView.centerY).with.offset(-5);
    }];

    self.addressLineTwoLabel = [UILabel new];
    self.addressLineTwoLabel.textAlignment = NSTextAlignmentCenter;

    [self.contentView addSubview:self.addressLineTwoLabel];

    [self.addressLineTwoLabel makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.addressLineOneLabel.bottom).with.offset(10);
        make.left.equalTo(self.contentView).with.offset(10);
        make.right.equalTo(self.contentView).with.offset(-10);
        make.bottom.equalTo(self.contentView).with.offset(-10);
    }];
    
At first, this resulted in a constraint error being shown. However, I set the background color for one of the labels and then the error disappeared and after removing the background color, it's stayed away so I don't have my exact error message. [Here's an error from someone else experiencing a similar issue though](http://stackoverflow.com/questions/25463057/uitableviewcell-with-autolayout-contentview-width-constraint-failure):

	Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
	(
	    "<MASLayoutConstraint:0x7ff4842551e0 UILabel:self.titleLabel.leading == UITableViewCellContentView:self.contentView.leading + 12>",
	    "<MASLayoutConstraint:0x7ff484255240 UILabel:self.titleLabel.trailing == UITableViewCellContentView:self.contentView.trailing - 12>",
	    "<NSLayoutConstraint:0x7ff484256df0 UITableViewCellContentView:self.contentView.width ==>"
	)
	
Setting the background color of the label showed me that my constraints aren't being set properly as the colour was only as big as the text in the label. Also, setting the text alignment to center also confirmed this as the text is not centered in the `contentView` at all.

**Comment by wongzigii** [comment]
Same issue here. Try @slhodson969 's but not luck.

**Comment by coldmn3** [comment]
add the constraints in updateConstraints solve the problem

**Comment by IUyuRtBbyQnRCI** [comment]
try rewrite ` -sizeThatFits:` for Cell

**Comment by wuzhengbo7** [comment]
I end up make the priority between [751,999]. solve the problem
