### ISSUE TITLE
'Redefinition of constraint relation'

### ISSUE THREAD

**Issue by masaniparesh** [Masonry/Masonry#136]
Hello Guys, I have a situation where I need to update only one one constraint for couple of Labels. These labels belong to UITableViewCell so to optimize updating constraints when we have a 1000s of cells, I attempted to do it following way but unfortunately it doesn't allow me to set reference - 'Redefinition of constraint relation'. Can you help please?

Complete failure message;
-----------------------------------

    *** Assertion failure in -[MASViewConstraint equalToWithRelation], 
    *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Redefinition of constraint relation'

Code:
-------
    @interface MessageCell()
    @property (nonatomic) MASConstraint *messageLabelTopConstraint;
    @property (nonatomic) MASConstraint *separatorViewTopConstraint;
    @end

    @implementation MessageCell

    - (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
        self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
        if (self) {
            ........
            self.messageLabel = [UILabel new];
            [self addSubview:self.messageLabel];
            
            [self.messageLabel mas_makeConstraints:^(MASConstraintMaker *make) {
                self.messageLabelTopConstraint = make.top.equalTo(self.senderLabel.mas_bottom).offset(10);
                make.left.equalTo(self).offset(30);
                make.right.equalTo(self.dateLabel.mas_left).offset(-10);
            }];
            
            self.separatorView = [UIView new];
            [self addSubview:self.separatorView];
            
            [self.separatorView mas_makeConstraints:^(MASConstraintMaker *make) {
                self.separatorViewTopConstraint = make.left.equalTo(self);
                make.top.right.equalTo(self);
                make.height.equalTo(@1);
            }];
        }
        return self;
    }

    - (void)updateConstraintsWithoutSender {
        [self.messageLabelTopConstraint uninstall];
        self.messageLabelTopConstraint.equalTo(self.senderLabel);
        [self.messageLabelTopConstraint install];
    
        [self.separatorViewTopConstraint uninstall];
        self.separatorViewTopConstraint.equalTo(self.messageLabel);
        [self.separatorViewTopConstraint install];
    }

    - (void)updateConstraintsWithSender {
        [self.messageLabelTopConstraint uninstall];
        self.messageLabelTopConstraint.equalTo(self.senderLabel.mas_bottom).offset(10); --> NSAssert fails here
        [self.messageLabelTopConstraint install];
    
        [self.separatorViewTopConstraint uninstall];
        self.separatorViewTopConstraint.equalTo(self);
        [self.separatorViewTopConstraint install];
    }
    @end

Following works but not optimized solution;
---------------------------------------------------------

    - (void)updateConstraintsWithoutSender {
        [self.messageLabel mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.senderLabel);
            make.left.equalTo(self).offset(30);
            make.right.equalTo(self.dateLabel.mas_left).offset(-10);
        }];
        
        [self.separatorView mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.top.right.equalTo(self);
            make.left.equalTo(self.messageLabel);
            make.height.equalTo(@1);
        }];
    }

    - (void)updateConstraintsWithSender {
        [self.messageLabel mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.senderLabel.mas_bottom).offset(10);
            make.left.equalTo(self).offset(30);
            make.right.equalTo(self.dateLabel.mas_left).offset(-10);
        }];
        
        [self.separatorView mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.top.left.right.equalTo(self);
            make.height.equalTo(@1);
        }];
    }

**Comment by cloudkite** [comment]
@masaniparesh currently an uninstalled constraint cannot be reused.

instead of
```
[self.messageLabelTopConstraint uninstall];
self.messageLabelTopConstraint.equalTo(self.senderLabel);
```

try 
```
[self.messageLabelTopConstraint uninstall];
[self.separatorView mas_makeConstraints:^(MASConstraintMaker *make) {
      self.separatorViewTopConstraint = make.left.equalTo(self.senderLabel);
}];
```
