### ISSUE TITLE
How to describe that a subview top space constraint is 20% of its superview height ?

### ISSUE THREAD

**Issue by onmyway133** [Masonry/Masonry#143]
How to describe that a subview 's `top space constraint to superview` is 20% of its superview height ?

This will raise an exception
```
[subview mas_makeConstraints:^(MASConstraintMaker *make) {
     make.top.equalTo(superview.mas_height).multipliedBy(20/100.0);
}];
```

Workaround is to to this

```
[subview mas_makeConstraints:^(MASConstraintMaker *make) {
     make.centerY.equalTo(superview.mas_centerY).multipliedBy(40/100.0);
}];
```

Not sure if there are better ways

**Comment by cloudkite** [comment]
you cannot relate size attributes (height, width) to position attributes (left, top etc)

If you wanted 20% margin on both top and bottom you could create a constraint which is

make.height.equalTo(superview.mas_height).multipliedBy(60/100.0);
make.center.equalTo(superview.mas_center);
