### ISSUE TITLE
There is a chance to crash on ios6

### ISSUE THREAD

**Issue by peakerWd** [Masonry/Masonry#144]
Hello,there is an issue on ios6,when I use Masonry,there is a chance to crash,if I have a wrong use please tell me，I will always wait for your reply,Thanks!

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString _forgetDependentConstraint:]: unrecognized selector sent to instance 0x1de71390'

 ( 
0   CoreFoundation                      0x3265e2a3  + 162
1   libobjc.A.dylib                     0x3a37b97f objc_exception_throw + 30
2   CoreFoundation                      0x32661e07  + 170
3   CoreFoundation                      0x32660531  + 392
4   CoreFoundation                      0x325b7f68 _CF_forwarding_prep_0 + 24
5   UIKit                               0x3489f475  + 132
6   UIKit                               0x3489fb17 -[UIView _removeConstraint:] + 274
7   baiduHi                             0x00473107 -[MASViewConstraint uninstall] + 82
8   CoreFoundation                      0x326529a1  + 396
9   CoreFoundation                      0x325b4b6b -[NSArray enumerateObjectsWithOptions:usingBlock:] + 62
10  baiduHi                             0x00138f71 -[CharacterCell updateConstraints] + 52
11  UIKit                               0x348a4e47 -[UIView _updateConstraintsIfNeeded] + 182
12  UIKit                               0x344693f3 -[UIView layoutBelowIfNeeded] + 66
13  UIKit                               0x3449e653 -[UITableView _updateWithItems:updateSupport:] + 3554
14  UIKit                               0x3449abf9 -[UITableView _endCellAnimationsWithContext:] + 7812

**Comment by kouky** [comment]
@peakerWd sorry but I cannot discern anything useful from the details you provided.
