### ISSUE TITLE
TableViewCell auto height with it's subview

### ISSUE THREAD

**Issue by kanbekotori** [Masonry/Masonry#146]
I use auto layout to make tableviewcell height to auto, and actually work. But when i click a button in cell to another viewcontroller and come back, the cell height is incorrect. Here is my demo https://github.com/kanbekotori/AutoLayoutDemo.git, please help me, Thanks!

**Comment by cloudkite** [comment]
You have not implemented `tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath`
