### ISSUE TITLE
masonry weird spaces

### ISSUE THREAD

**Issue by lironrichkid** [Masonry/Masonry#149]
Hi I put masonry code everything looks alright there are no console errors from javascript type etc.
but nothing happens (means there is no absolute on divs)
why?
there is something i lose here?

http://www.reading3.co.il/he/company/a/gallery/?ContentID=295
thanks

**Comment by lluisgerard** [comment]
I think you are confused with a Javascript library. This github project is for the iOS library.

**Comment by lironrichkid** [comment]
what did you mean?

**Comment by lluisgerard** [comment]
You are talking about javascript and linking to a website.
This is for the Objective-C code library Masonry and has nothing to do with the Javascript one.

**Comment by lironrichkid** [comment]
i am not using any objective c who are you?

**Comment by lluisgerard** [comment]
You have to post this issue here: https://github.com/desandro/masonry Thanks
