### ISSUE TITLE
Cannot compile Success in xcode 5.1.1

### ISSUE THREAD

**Issue by 858665536** [Masonry/Masonry#152]
There are three methods "isActive","activate" and "deactivate" in the MASViewConstraint.m.  The property  active  says  NS_AVAILABLE(10_10, 8_0).  

And I add  
#ifdef __IPHONE_8_0
  self.layoutConstraint.active = NO;
#endif
to use your wonderful Masony in Xcode 5.1.1,I wonder if there is another  good way to solve the problem

**Comment by cloudkite** [comment]
@858665536 v0.6 introduced a couple of features which require xcode6. If you still wish to use xcode5 please use an older version of Masonry
