### ISSUE TITLE
Ios example for a horizontal scroll view layout?

### ISSUE THREAD

**Issue by ericlewis** [Masonry/Masonry#154]
I've tried modifying the code in the vertical scroll view example to layout horizontally, which works, but it seems that I lose interaction when attempting this. When we layout the same views vertically then the interaction returns. Any help?

**Comment by ericlewis** [comment]
https://gist.github.com/0oneo/6fe093bfb8f2c71b69ef

**Comment by onmyway133** [comment]
Maybe this can help you http://www.fantageek.com/1237/make-tutorial-screen-with-uiscrollview-and-autolayout/
