### ISSUE TITLE
Layout a number of buttons equally.

### ISSUE THREAD

**Issue by ericlewis** [Masonry/Masonry#155]
I would like to layout 3 buttons (similar to a tab bar) with equal widths depending on the number of items to be displayed. is there any examples of this?

**Comment by ericlewis** [comment]
keep in mind, the number of buttons could change. so we want either 1 or 5 items, which can have variables widths depending on the amount existing.

**Comment by cloudkite** [comment]
@ericlewis one approach is to set all views so they have equal widths then just define the gaps in between them. Autolayout will work out the rest for you

```
    NSArray *views = @[view1, view2, view3];
    UIView *lastView;
    CGFloat margin = 10;
    UIView *superview = self;
    
    for (UIView *view in views) {
        NSMutableArray *otherViews = [[NSMutableArray alloc] initWithArray:views];
        [otherViews removeObject:view];
        [view mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(lastView ? lastView.right : superview.left).offset(margin);
            make.width.equalTo(otherViews);
            make.height.equalTo(100);
        }];
        
        lastView = view;
    }
    
    [lastView makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(-margin);
    }];
```

**Comment by ericlewis** [comment]
The problem here is the number of buttons can change, so the width can change. I think the correct approach is relayout when the possible width may change. We also don't want any sort of gaps. We solved it by doing a remake when the size of the display changes. Still AL. But not as beautiful as pure AL. 



—

**Comment by cloudkite** [comment]
views is an array you can have as many objects as you like in it and they layout will still work fine

**Comment by ericlewis** [comment]
Ahh. I see what you are proposing. We may give it a shot. It's not that different from setting up a scroll view with masonry, but the widths will need be flexible in a way. So pin each to the left then the final to the right, and it'll work itself out? 



—

**Comment by cloudkite** [comment]
Yup if you don't explicitly set a dimension like width, AL will try infer it from other dimensions. Good luck!

**Comment by lluisgerard** [comment]
I also had done the same without specifying a margin and using empty views (that I call flexViews :smile: ). Is not something I just made up, this is from Apple documentation: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/AutoLayoutbyExample/AutoLayoutbyExample.html#//apple_ref/doc/uid/TP40010853-CH5-SW8

I even played with the first and last views being equal between them with "dividedBy" and the ones in the middle just regular, etc.. 

The nice thing about this, is that the more views you have in the array, the little the space between them.

**Comment by iBenjamin** [comment]
@lluisgerard well done,can you show us the code?

**Comment by lluisgerard** [comment]
@iBenjamin Of course! I have it in Swift/Snap right now and the code can be improved for sure, but you get the idea:
```
extension UIView {
    /**
    Adds flexible views in between the views passed on the array using Autolayout (Snap)
    
    :param: views    Views to add
    :param: viewSize Size of each view
    */
    func sys_addFlexibleViewsHorizontally(views: [UIView], innerFlexesDividedBy: CGFloat) {

        if views.count == 0 {
            return
        }

        let superview = self

        // Create and add first flexible views
        let flexibleLeft = UIView()
        flexibleLeft.backgroundColor = UIColor.clearColor()
        superview.addSubview(flexibleLeft)
        let flexibleViews : [UIView] = {
            var array = [UIView]()
            for view in views {
                let flexibleView = UIView()
                flexibleView.backgroundColor = UIColor.clearColor()
                array.append(flexibleView)
                superview.addSubview(flexibleView)
                superview.addSubview(view)
            }
            return array
        }()

        // First View
        if let view = views.first {
            // With the first Left Flex
            flexibleLeft.snp_makeConstraints{ (make) -> () in
                make.centerY.equalTo(superview)
                make.left.equalTo(superview)
                let lastFlex = flexibleViews.last
                make.width.equalTo(lastFlex!)
                make.right.equalTo(view.snp_left)
            }
        }

        // Add subviews and adjust to flexible
        let count = views.count
        var index = 0
        for view in views {
            
            // Right
            let rightFlex = flexibleViews[index]
            
            // Next (left) flex
            var nextFlex : UIView? = {
                if index == count - 1 {
                    return nil
                } else {
                    return flexibleViews[index + 1]
                }
            }()
            
            // View Constriant
            view.snp_makeConstraints{ (make) -> () in
                make.centerY.equalTo(superview)
                make.right.equalTo(rightFlex.snp_left)
            }
            
            rightFlex.snp_makeConstraints{ (make) -> () in
                
                make.centerY.equalTo(superview)
                
                if let nextFlex = nextFlex {

                    let leftFlex : UIView = {
                        if index == 0 {
                            return flexibleLeft
                        } else {
                            return flexibleViews[index - 1]
                        }
                    }()

                    if index == 0 {
                        // First right flex is divided by innerFlexesDividedBy...
                        make.width.equalTo(leftFlex).dividedBy(innerFlexesDividedBy)
                    } else {
                        // ...the rest take the width from the previous one
                        make.width.equalTo(leftFlex)
                    }

                    // Next View
                    var nextView : UIView? = {
                        if index == count - 1 {
                            return nil
                        } else {
                            return views[index + 1]
                        }
                    }()
                    if let nextView = nextView {
                        make.right.equalTo(nextView.snp_left)
                    }
                    
                } else {
                    
                    // Last flex just sticks to the right
                    make.right.equalTo(superview)
                }
                
            }
            
            index++
            
        }
        
    }

}
```

**Comment by Jacky9GAG** [comment]
A shorter version 

   if let descriptions = configuration.appDescriptions {
            
            descriptions.enumerate().forEach { index, description in
                
                let label = UILabel()
                scrollContentView.addSubview(label)
                descriptionLabels.append(label)
                
                label.snp_makeConstraints { make in
                    
                    if index == 0 {
                        
                        make.left.equalTo(scrollContentView)
                        
                    } else {
                        
                        let previousLabel = descriptionLabels[index - 1]

                        make.left.equalTo(previousLabel.snp_right)

                        if index == descriptions.count - 1 {
                            make.right.equalTo(scrollContentView)
                        }
                    }
                    
                    make.top.bottom.height.equalTo(scrollContentView)
                    make.width.equalTo(view)
                    
                }
            }
        }

**Comment by thewhitewood** [comment]
Shouldn't you just use a UIStackView?

**Comment by lluisgerard** [comment]
@thewhitewood This conversation started when iOS 8 was the last release (meaning you probably had to maintain iOS 7) and UIStackView was released with iOS 9 (meaning that maybe you could start using it when iOS 10 was around). That means that developers could start using UIStackView on serious project around October-2016.

Short answer... use UIStackView if you can 😅 probably this thread should be closed/don't allow new comments

**Comment by InjoyDeng** [comment]
```
make.top.bottom.height.equalTo(scrollContentView)
make.width.equalTo(view)
```
@Jacky9GAG what is the view?
