### ISSUE TITLE
Remove release build warning about unused variable in MASConstraintMaker.m

### ISSUE THREAD

**Issue by iosdev-republicofapps** [Masonry/Masonry#156]
Hi,

Masonry is awesome by the way - really helpful and I'm loving it!

I try to create warning-free builds.  However, when building a release build, the following code generates an "unused variable" warning because the `anyAttribute` variable is only used in the assert (and asserts are turned off and compile to nothing in release builds):
```
// In MASConstraintMaker.m
- (MASConstraint *)addConstraintWithAttributes:(MASAttribute)attrs {
    MASAttribute anyAttribute = MASAttributeLeft | MASAttributeRight | MASAttributeTop | MASAttributeBottom | MASAttributeLeading | MASAttributeTrailing | MASAttributeWidth | MASAttributeHeight | MASAttributeCenterX | MASAttributeCenterY | MASAttributeBaseline;
    
    NSAssert((attrs & anyAttribute) != 0, @"You didn't pass any attribute to make.attributes(...)");
```

You can fix this by adding the following two compiler directives/preprocessor commands:
```
- (MASConstraint *)addConstraintWithAttributes:(MASAttribute)attrs {
#ifdef ENABLE_NS_ASSERTIONS
    MASAttribute anyAttribute = MASAttributeLeft | MASAttributeRight | MASAttributeTop | MASAttributeBottom | MASAttributeLeading | MASAttributeTrailing | MASAttributeWidth | MASAttributeHeight | MASAttributeCenterX | MASAttributeCenterY | MASAttributeBaseline;
    
    NSAssert((attrs & anyAttribute) != 0, @"You didn't pass any attribute to make.attributes(...)");
#endif
```

This ensures that the `anyAttribute` variable is defined when it's needed (when assertions are defined and the subsequent NSAssert needs the variable) and is not defined when not needed (when asserts are off).

This seems like the safest way to do this: using `#ifdef DEBUG` wouldn't work if assertions were turned on in non-debug builds for some reason and wrapping the two statements in a clang pragma to disable the warning looks uglier.

I'd be happy to create a pull request for this change if you'd like.  Please advise.

But it's important to have warning-free builds.  :-)

Thanks!

**Comment by cloudkite** [comment]
This has been fixed in https://github.com/Masonry/Masonry/commit/1232b3e6e8cf8a2c19c008651ac738afe65e05bc


Thanks!

**Comment by iosdev-republicofapps** [comment]
Thanks!  Is it possible to cut a 0.6.1 build for this?  :-)

**Comment by cloudkite** [comment]
Done :)
