### ISSUE TITLE
how to set tow subview horizontal alignment?

### ISSUE THREAD

**Issue by iBenjamin** [Masonry/Masonry#158]
![image](https://cloud.githubusercontent.com/assets/9389813/6037872/1464fb42-ac93-11e4-8b15-c44d79d57d60.png)

**Comment by Taarna** [comment]
```
[view2 mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.equalTo(view1.mas_top);
}];
```

**Comment by eytanbiala** [comment]
@cloudkite How would you set constraints if view2 was a constant width, and you wanted the view1 to fit the rest of the width? (Assuming these views are in a superview with its own constraint for the width)

**Comment by cloudkite** [comment]
[view1 mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.equalTo(view2.right).insets(padding);
    make.right.equalTo(superview.right).insets(padding);
}];

**Comment by eytanbiala** [comment]
Sorry, I'm still learning how to use AutoLayout, can you explain why view1.left = view2.right?

**Comment by Taarna** [comment]
@eytanbiala view2 will be on the left side of the superview and view1 will be on the right.

![img](https://cloud.githubusercontent.com/assets/4928442/6765143/9f943760-cfd3-11e4-8a18-aa6fd8614097.png)

**Comment by eytanbiala** [comment]
Oh ok that makes sense, thanks for clarifying!

**Comment by nsdictionary** [comment]
how can i user Masonry explain views position relationship?

forexample vfl:V:|-10-[view1]-10-[view2]-10-|?

how to explain this some views's position relationship?

because i fell,Masonry’s make function is single use for one view
