### ISSUE TITLE
Centering a view in between two others

### ISSUE THREAD

**Issue by omergul123** [Masonry/Masonry#160]
I'm trying to center my view in between two other views.

Basically, I want my back button to be vertically aligned in center, between inviteButton and mascotView. But in my way it sits on top of mascotView. Is there a way for this?

   [self.backButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(superview);
        make.top.greaterThanOrEqualTo(self.inviteButton.mas_bottom);
        make.bottom.lessThanOrEqualTo(self.mascotView.mas_top);
    }];

**Comment by Taarna** [comment]
You could center the back button and then arrange the other two elements like this:

```
// back button
	[view1 mas_makeConstraints:^(MASConstraintMaker *make) {

		// set width and height
		
		make.centerY.equalTo(superview);
	}];
	
// invite button
	[view2 mas_makeConstraints:^(MASConstraintMaker *make) {

		// set width and height
		
		make.bottom.equalTo(view1.mas_top).offset(-padding);
	}];

// mascot view
	[view3 mas_makeConstraints:^(MASConstraintMaker *make) {

		// set width and height
		
		make.top.equalTo(view1.mas_bottom).offset(padding);
	}];
```

**Comment by omergul123** [comment]
But you are centering the back button to the center of superview. Instead I want a fixed position for invite and mascot view and I want back button to just sit in between them. So even if the height of the screen changes (iPhone4 vs iPhone5 vs iPhone6) back button simply will be displayed where it should be best, only the top and bottom margin will change for back button according to the screen size.

**Comment by Taarna** [comment]
You could add a new view whose top will be equal to invite's bottom and the bottom will be equal to mascot's top. Add back button as its subview and center it.

Second thing that comes to my mind are spacing views. Create two transparent views. Place the first one between invite and back and the second one between back and mascot.
This solution is described in [Apple's documentation](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/AutoLayoutbyExample/AutoLayoutbyExample.html#//apple_ref/doc/uid/TP40010853-CH5-SW7).
