### ISSUE TITLE
in (lldb)  can't po object

### ISSUE THREAD

**Issue by Coneboy-k** [Masonry/Masonry#162]
Sometime I can't use po object in lldb.

lldb **print** log 

    (lldb) po _delegate
    error: instance method 'left' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'top' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'right' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'bottom' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'centerX' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'centerY' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'width' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'height' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'left' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'top' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'right' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'bottom' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'width' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    error: instance method 'height' has incompatible result types in different translation units ('CGFloat' (aka 'float') vs. 'MASViewAttribute *')
    note: instance method 'left' also declared here
    note: instance method 'top' also declared here
    note: instance method 'right' also declared here
    note: instance method 'bottom' also declared here
    note: instance method 'centerX' also declared here
    note: instance method 'centerY' also declared here
    note: instance method 'width' also declared here
    note: instance method 'height' also declared here
    note: instance method 'left' also declared here
    note: instance method 'top' also declared here
    note: instance method 'right' also declared here
    note: instance method 'bottom' also declared here
    note: instance method 'width' also declared here
    note: instance method 'height' also declared here
    error: 14 errors parsing expression

**Comment by cloudkite** [comment]
looks like you have another UIView category which adds left, right, centerX etc properties which is clashing with Masonry

**Comment by Coneboy-k** [comment]
Yeah，Indeed there is a UIView category  in my project.    THANKS!

**Comment by berryhunt** [comment]
How would one resolve this issue, when there is another category with the same variables involved? Other than taking out the other category from the workspace...
