### ISSUE TITLE
Insets work on left and right, but not leading and trailing.

### ISSUE THREAD

**Issue by montehurd** [Masonry/Masonry#165]
This works:
make.**left**.and.**right**.equalTo(superview).insets(UIEdgeInsetsMake(0, 12, 0, 12));

But this doesn't seem to:
make.**leading**.and.**trailing**.equalTo(superview).insets(UIEdgeInsetsMake(0, 12, 0, 12));

I use leading and trailing (instead of left and right) for RTL language support. I'm new to Masonry so apologies if there is another way of doing this.

**Comment by AugustRush** [comment]
Top and bottom


发自我的 iPhone

**Comment by montehurd** [comment]
Umm... Leading and Trailing controls the sides, not the top and bottom.

**Comment by montehurd** [comment]
Oh, maybe you meant did I forget to constrain the top and bottom? No, I didn't, I just isolated the example to a single line.

**Comment by cloudkite** [comment]
@montehurd Whoops the code doesn't currently apply insets to leading and trailing attributes.

**Comment by cloudkite** [comment]
Here is the relevant line https://github.com/Masonry/Masonry/blob/master/Masonry/MASViewConstraint.m#L234

Would you like to submit a PR? Currently swamped at work so I probably won't have time until next week.

**Comment by montehurd** [comment]
Submitted PR. Seems to work :)
