### ISSUE TITLE
Find a crash

### ISSUE THREAD

**Issue by liushaoxing** [Masonry/Masonry#166]
It's crashed when I click the view MarginView.Maybe cause by the code  "        view.layoutMargins = UIEdgeInsetsMake(5, 10, 15, 20); "  crash report -[UIView setLayoutMargins:]: unrecognized selector sent to instance 0x1755e5a0

**Comment by cloudkite** [comment]
The Masonry library does not add a method called setLayoutMargins to UIView.

**Comment by liushaoxing** [comment]
@cloudkite Find.May I ask you another question?  the mesthod +(BOOL)requiresConstraintBasedLayout should be use in what kind of situation?

**Comment by cloudkite** [comment]
This tells UIKit it needs to call updateConstraints

see https://github.com/Masonry/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleUpdateView.m

**Comment by liushaoxing** [comment]
@cloudkite Thank you .
