### ISSUE TITLE
Vertically stacking several UIViews in their superview's center?

### ISSUE THREAD

**Issue by matt-curtis** [Masonry/Masonry#167]
Is this easily possible in Masonry? I have three UIViews of varying height that I would like to vertically stack on top of each other in the center of their parent's superview (as a whole, vs separate views). The idea came to me that I could center the middle view, and base the tops and bottoms of the views above and below it to do this, but that only works if the views are all of the same height.

Example:

![mockup](https://cloud.githubusercontent.com/assets/1414704/6491386/724dc370-c272-11e4-9e53-c6b274638ef5.png)

Any ideas?

**Comment by cloudkite** [comment]
@matt-curtis might need to add `container` view which contains the three subviews and is centered in the superview

**Comment by matt-curtis** [comment]
@cloudkite OK, I was considering that too. Is this the correct approach for the superview?

`make.height.equalTo(@[ subviewOne.mas_height, @(spacing), etc., repeat... ])`

I tried this with the three subviews being labels but the heights did not seem right.

**Comment by cloudkite** [comment]
No that's not going to have the affect you want. Values within an array are not additive. You shouldn't need to define the superview height. Let AL figure it out for you

**Comment by matt-curtis** [comment]
@cloudkite OK, how should I tell it that it's height = height of subviews/content? Sorry if I'm a little clueless.

**Comment by cloudkite** [comment]
AL will figure it out itself if you have setup up the subview constraints correctly

**Comment by cloudkite** [comment]
```
    
    UIView *container = UIView.new;
    container.backgroundColor = UIColor.greenColor;
    container.layer.borderColor = UIColor.blackColor.CGColor;
    container.layer.borderWidth = 2;
    [self addSubview:container];

    UIView *view1 = UIView.new;
    view1.backgroundColor = UIColor.greenColor;
    view1.layer.borderColor = UIColor.blackColor.CGColor;
    view1.layer.borderWidth = 2;
    [container addSubview:view1];

    UIView *view2 = UIView.new;
    view2.backgroundColor = UIColor.redColor;
    view2.layer.borderColor = UIColor.blackColor.CGColor;
    view2.layer.borderWidth = 2;
    [container addSubview:view2];

    UIView *view3 = UIView.new;
    view3.backgroundColor = UIColor.blueColor;
    view3.layer.borderColor = UIColor.blackColor.CGColor;
    view3.layer.borderWidth = 2;
    [container addSubview:view3];

    UIView *superview = container;
    UIEdgeInsets padding = UIEdgeInsetsMake(15, 10, 15, 10);
    
    [container mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(self);
    }];


    [view1 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.and.left.equalTo(superview).insets(padding);
        make.bottom.equalTo(view3.mas_top).insets(padding);
        make.right.equalTo(view2.mas_left).insets(padding);
        
        make.width.equalTo(100);
        make.height.equalTo(100);
    }];

    [view2 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.and.right.equalTo(superview).insets(padding);

        make.left.equalTo(view1.mas_right).insets(padding);
        make.bottom.equalTo(view3.mas_top).insets(padding);
        make.width.equalTo(view1.mas_width);
        
        make.height.equalTo(90);
    }];

    [view3 mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(view1.mas_bottom).insets(padding);

        make.left.right.and.bottom.equalTo(superview).insets(padding);
        
        make.height.equalTo(60);
    }];
```

**Comment by matt-curtis** [comment]
Working with UILabels with dynamic height, is this the correct way? (This isn't the exact code but you get the idea).

	NSNumber *spacing = 8;

	//	Label One

	[labelOne setContentHuggingPriority:REQUIRED forAxis:VERTICAL]; // this is so that the height = text height

	[labelOne mas_makeConstraints:^(MASConstraintMaker *make){
		make.width.and.top.and.left.equalTo(superview);
	}];

	//	Label Two

	[labelTwo setContentHuggingPriority:REQUIRED forAxis:VERTICAL];

	[labelTwo mas_makeConstraints:^(MASConstraintMaker *make){
		make.width.and.left.equalTo(superview);
		make.top.equalTo(labelOne.mas_bottom).offset(spacing);
	}];

	//	Label Three

	[labelThree setContentHuggingPriority:REQUIRED forAxis:VERTICAL];

	[labelThree mas_makeConstraints:^(MASConstraintMaker *make){
		make.width.and.left.equalTo(superview);
		make.top.equalTo(labelTwo.mas_bottom).offset(spacing);
	}];

**Comment by cloudkite** [comment]
UILabels with AL :sob:  That is a whole another world of pain, my condolences

**Comment by matt-curtis** [comment]
Now I'm scared. Well, we'll see what comes of it. I have a method of doing this with pure frames that might not such too much if I can't get this working
