### ISSUE TITLE
You are Too strong!!! I have a question

### ISSUE THREAD

**Issue by nsdictionary** [Masonry/Masonry#169]
感谢作者！我佩服的五体投地！

Thank you first of all, your framework is powerfull！！！

i’m chinese in chengdu ,my english is very poor,so my description must have many syntax error, but i very hope that you cloud read over my question,and give me a response,thank you very much, and happy new sheep year!!!!!

:)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    :)    

but,i have a question,

1.some method has two child method,one don,t have prefix “mas_”,and another has prefix “mas_”,

for exaple: 
equal, mas_equal
offset,mas_offset

what does  “mas_” mean? why a method has another method with prefix “mas_”??

2.we add constraint use [view mas_makeConstraints:];   but sometimes i need add constraint between two views or even more,

for example,  i want this effect (views  add constraints not one view) if i use apple’s vfl,i can do it like this:

@“H:|-0-[view1]-10-[view2]-10-[view3]-10-[view4]-….-0-|”

3.there has some method named “and” “with”,i know their usage,but if i don’t use them,i could receive the save result,i fell “and” “with” is useless???
example: 
make.redview.width.and.height.equalTo(self.view);
                          || (the same?)
make.redview.width.height.equalTo(self.view);

4.what different in left/leftMargin  top/topMargin bottom/bottomMargin right/rightMargin ?
i have test ,but i find out they are same???

thank you!!!

**Comment by cloudkite** [comment]
1. Its considered good practice to prefix your method names if you are extending a built in class with a `category`

2. Please read the readme

3. Yes they have no effect its just semantic

4. https://github.com/Masonry/Masonry/pull/163
