### ISSUE TITLE
couldn't find a common superview 

### ISSUE THREAD

**Issue by terminatorover** [Masonry/Masonry#170]
I'm getting "'couldn't find a common superview " error. All i did was create in a view in a view controller and simply tried to use the API. I'm not sure what i'm missing, here is the snippet. Note I already added the _sectionHeader to the self.view
    [_sectionHeader mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view.mas_top).with.offset(padding);
        make.left.equalTo(self.view.mas_right).with.offset(padding);
        make.left.equalTo(self.view.mas_leading).with.offset(padding);
        make.height.equalTo(@50);
    }];

**Comment by lluisgerard** [comment]
Sounds strange but I noticed that you are setting the left constrain twice and don't underztand what are you trying to do actually. Can you try to fix that first and see if it solves the issue?

**Comment by terminatorover** [comment]
That was a silly mistake on my part, Thank you sir.

**Comment by lluisgerard** [comment]
@terminatorover you're welcome :) please close the issue if everything is fine now, thanks!
