### ISSUE TITLE
Matching scrollView.contentOffset

### ISSUE THREAD

**Issue by eytanbiala** [Masonry/Masonry#171]
I am trying to make a view, which is a subview of a scrollview, stay in the same horizontal position when zooming or scrolling the scrollview. So, what is the correct way to horizontally align a scrollview subview to match the contentOffset. I tried doing this, but it doesn't actually work since the contentOffset changes:
````
make.left.equalTo(@(self.mailView.webView.scrollView.contentOffset.x));
`````

Would it make sense to always update constraints in `scrollViewDidScroll` and `scrollViewDidZoom` with the new contentOffset?

**Comment by CraigSiemens** [comment]
Why does it need to be a subview of the scrollview? If it was above the scrollview, that would be the easiest way to prevent it from moving when you scroll.

**Comment by eytanbiala** [comment]
It's a subview of the scrollview since it needs to be able to scroll up and down.

**Comment by CraigSiemens** [comment]
If you move your view outside of the scrollview, keeping it scrolling vertically is pretty easy. You'll just need to add a vertical positioning constraint to a view in the scrollview. Say you've got the following view hierarchy.

```
- view
    - verticalScrollingView (the view you want to only scroll vertically)
    - scrollView
        - scrollViewSubView
```

Then you should just need to add two constraints for the horizontal and vertical positions.

```objc
[verticalScrollingView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.equalTo(self.scrollViewSubView.mas_top);
    make.left.equalTo(self.view.mas_left);
}];
```

**Comment by eytanbiala** [comment]
Thanks, I'll try that out. Do you know by any chance how it will affect zooming in the scrollview?

To clarify my goal here - I am implementing something similar to the Apple Mail app, where the scrollview is a UIWebView scrollview, and the view that I'm referring to is the "header" portion, which shows recipients, date, subject, etc. Adding the view as a subview to the webview scrollview was recommended by a few people on SO and Apple forums, for example here - http://stackoverflow.com/questions/10434444/zoom-a-uiwebview-like-ios-mail-app
