### ISSUE TITLE
Newbie Question. Elements are not appearing on screen. 

### ISSUE THREAD

**Issue by Jamongkad** [Masonry/Masonry#173]
Hi great library btw! I subclassed a UIView and called it ButtonsView....

    @implementation ButtonsView
    - (id)init {
    if(self = [super init]) {
        UIButton *raiseButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [raiseButton setTitle:@"Raise" forState:UIControlStateNormal];
        [self addSubview:raiseButton];
        
        UIButton *centerButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [centerButton setTitle:@"Center" forState:UIControlStateNormal];
        [self addSubview:centerButton];
        
        UIButton *lowerButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [lowerButton setTitle:@"Lower" forState:UIControlStateNormal];
        [self addSubview:lowerButton];
        
        [lowerButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(self).with.offset(10.0);
        }];
        [centerButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerX.equalTo(self);
        }];
        [raiseButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(self).with.offset(-10);
        }];
        
        self.buttonViews = @[ raiseButton, lowerButton, centerButton ];
    }
    
    return self;
    }

@end

I then have a UIViewController 

    #import "AmountViewController.h"
    #import "ButtonsView.h"

    @interface AmountViewController ()
    @end

    @implementation AmountViewController

    - (void)viewDidLoad {
        [super viewDidLoad];
        ButtonsView *buttons = [[ButtonsView alloc] init];
        buttons.frame = CGRectMake(200, 200, 312, 50);
        [self.view addSubview:buttons];
    }
    @end

I can't see my button view anywhere on the screen...

**Comment by cloudkite** [comment]
@Jamongkad your views are probably underconstrained, meaning they dont have enough constraints for AL to be able to determine their size. Trying adding borders to your views to see what is on screen and what isnt

**Comment by xieweizhi** [comment]
You didn't set each button size in ButtonsView.

**Comment by Jamongkad** [comment]
Hello thanks for the prompt replies. So here's my code...

    - (id)init {
    if(self = [super init]) {
        UIButton *raiseButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [raiseButton setTitle:@"Raise" forState:UIControlStateNormal];
        [raiseButton setFrame:CGRectMake(0, 0, 100, 20)];
        [raiseButton setBackgroundColor:[UIColor blueColor]];
        [self addSubview:raiseButton];
        
        UIButton *centerButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [centerButton setTitle:@"Center" forState:UIControlStateNormal];
        [centerButton setFrame:CGRectMake(0, 0, 100, 20)];
        [centerButton setBackgroundColor:[UIColor greenColor]];
        [self addSubview:centerButton];
        
        UIButton *lowerButton = [UIButton buttonWithType:UIButtonTypeSystem];
        [lowerButton setTitle:@"Lower" forState:UIControlStateNormal];
        [lowerButton setFrame:CGRectMake(0, 0, 100, 20)];
        [lowerButton setBackgroundColor:[UIColor orangeColor]];
        [self addSubview:lowerButton];
        
       
        [lowerButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.equalTo(self).with.offset(10.0);
        }];
        [centerButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerX.equalTo(self);
        }];
        [raiseButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(self).with.offset(-10);
        }];
      
        
        self.buttonViews = @[ raiseButton, lowerButton, centerButton ];
        
    }
    
    return self;
    }

I also added a red border around the BtnsView...

    ButtonsView *btns = [[ButtonsView alloc] initWithFrame:CGRectMake(0, 100, self.view.frame.size.width, 400)];
    [btns.layer setBorderColor:[UIColor redColor].CGColor];
    [btns.layer setBorderWidth:2.0f];
    [self.view addSubview:btns];

And still no buttons appearing on my UIViewController
![Imgur](http://i.imgur.com/jELTqzQ.png)

**Comment by cloudkite** [comment]
@Jamongkad what @xieweizhi said.
you need to size your buttons
