### ISSUE TITLE
Can I create a constraint without installing it immediately?

### ISSUE THREAD

**Issue by thanhtrdang** [Masonry/Masonry#175]
Hi,

I want create a constraint and I will install it later.
1. Have you got public API to do that?
2. I created some codes below:
MASConstraintMaker* constraintMaker = [[MASConstraintMaker alloc] initWithView:self.superview];
MASConstraint* heightContraint = constraintMaker.height.equalTo(self);
Is it good way to do it?

Thank you for your great library.
Thanh.

**Comment by cloudkite** [comment]
@thanhtrdang sorry no public api for doing that at the moment.
