### ISSUE TITLE
Feature request: ExcludingEdge supports.

### ISSUE THREAD

**Issue by VincentSit** [Masonry/Masonry#177]
I'm trying to migrate from PureLayout to Masonry.

PureLayout has a very nice feature, like the following:

```
[view autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsZero excludingEdge:ALTop];
```

Meaning of this code is similar to the following Masonry code:

```
make.edges.equalTo(view.superview).excluding(top);
```

Because Masonry does not support this feature, and if I want to achieve this layout, I have to do like this:

```
make.leading.equalTo(view.superview);
make.bottom.equalTo(view.superview);
make.trailing.equalTo(view.superview);
```

This is a very useful feature, hope Masonry can support this in the future.

**Comment by cloudkite** [comment]
you can use the following instead

```
make.leading.bottom.trailing.equalTo(view.superview)
```

**Comment by VincentSit** [comment]
This is awesome!!

Thanks @cloudkite
