### ISSUE TITLE
Can I access any View's constraint at run time and change it? 

### ISSUE THREAD

**Issue by liuxuan30** [Masonry/Masonry#179]
Hi there,
I am new to autoLayout, and I am considering rewriting my project using Masonry
 or other open source code, so I have to do some researching first.

One important thing is could I access any constraint at run time?

e.g. if I created below constraint:
```
make.width.lessThanOrEqualTo(@400)
```
Could I have any ways of accessing this Height constraint at run time in the future?  Note I don't want to do things like
```
self.property = make.width.lessThanOrEqualTo(@400)
```
because I don't want to store many properties. I just want change the height constraint at a given time and animate it. Thank you.

**Comment by cloudkite** [comment]
check out the examples theres a couple of ways to achieve this

https://github.com/Masonry/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleUpdateView.m

**Comment by liuxuan30** [comment]
You mean like this? make.width.lessThanOrEqualTo(self);

**Comment by cloudkite** [comment]
@liuxuan30 yep

**Comment by liuxuan30** [comment]
@cloudkite, yes, Thanks a lot!
