### ISSUE TITLE
No visible @interface for 'MASLayoutConstraint' declares the selector 'isActive'

### ISSUE THREAD

**Issue by sutekicut** [Masonry/Masonry#181]
Hi, 
Thank you for your great library.

when I try to build and Pod install , an error occurred.
could you give me a hand to solve this problems?

/********************************************************************
MASViewConstraint.m:293:31: Property 'active' not found on object of type 'MASLayoutConstraint *'
MASViewConstraint.m:112:41: No visible @interface for 'MASLayoutConstraint' declares the selector 'isActive'
********************************************************************/

**Comment by cloudkite** [comment]
You need to set your project base SDK to 8.0 and then set your deployment target to the appropriate value depending on what devices you need to target

https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html

**Comment by 858665536** [comment]
see issues #152

**Comment by sutekicut** [comment]
Hi, 
Thank you for your advices

I have decided to use the old version .

Thank you veryMuch!  It's work.
