### ISSUE TITLE
make.bottom.equalTo makes cell's hight increase a lot.

### ISSUE THREAD

**Issue by SeanChense** [Masonry/Masonry#183]
Here is a custom `UITableViewCell` with an `UIImageView` 
In UserInfoEditCell.m 

```
- (void)awakeFromNib {
     __weak typeof(self) weakSelf = self;
    [self.rightImageView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.bottom.equalTo(weakSelf.contentView);
    }];
    
}
```

If the cell is scrolled out the screen ,it's height will increase  a lot when back again.
But if use
`make.bottom.equalTo(weakSelf);` nothing will be happen.
Is any wrong?

**Comment by cloudkite** [comment]
Are you specifying a height in your UITableViewDelegate with 
```
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
```
