### ISSUE TITLE
how to get the height of root view without navigation bar and tab bar?

### ISSUE THREAD

**Issue by kyfxbl** [Masonry/Masonry#187]
hi, i used multipliedBy and mas_height to do the vetical align. what i want is: the above view takes 4/5 height of the screen, while the bottom view takes the rest 1/5

the code:
<pre>
[self addSubview:wallView];
        [self addSubview:bottomView];
        
        wallView.layer.borderWidth = 1.0f;
        wallView.layer.borderColor = [UIColor redColor].CGColor;
        bottomView.layer.borderWidth = 1.0f;
        bottomView.layer.borderColor = [UIColor yellowColor].CGColor;
        
        [wallView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(@0);
            make.left.equalTo(@0);
            make.width.equalTo(self.mas_width);
            make.height.equalTo(self.mas_height).multipliedBy(0.8f);
        }];
        
        [bottomView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(wallView.mas_bottom);
            make.left.equalTo(@0);
            make.width.equalTo(self.mas_width);
            make.height.equalTo(self.mas_height).multipliedBy(0.2f);
        }];
</pre>

and i add borders for both subviews, then i found that the height of navigation bar and tab bar are calculated...

![image](https://cloud.githubusercontent.com/assets/2126825/7116932/f9918a40-e227-11e4-9827-cf8fcdf88a64.png)

would you please tell me how to solve this problem? thanks a lot

**Comment by cloudkite** [comment]
you need to use layout guides. see https://github.com/Masonry/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleLayoutGuideViewController.m
