### ISSUE TITLE
[UIView mas_makeConstraints:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mytcer** [Masonry/Masonry#188]
I run the following code on iphone6，the program is crash，the error log is：`[UIView mas_makeConstraints:]: unrecognized selector sent to instance`

```
- (void)viewDidLoad {
    [super viewDidLoad];

    __weak ViewController *weakSelf = self;
    
    UIView *sv = [UIView new];
    sv.backgroundColor = [UIColor blackColor];
    [self.view addSubview:sv];
    
    [sv mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(weakSelf.view);
        make.size.mas_equalTo(CGSizeMake(300, 300));
    }];
}
```

**Comment by cloudkite** [comment]
have you imported the Masonry header?

**Comment by isbase** [comment]
i meet the same question. and I had import the Masonry header in the pch.

**Comment by isbase** [comment]
i meet the same question. and I had import the Masonry header in the pch.

**Comment by isbase** [comment]
i meet the same question. and I had import the Masonry header in the pch.

**Comment by xingheng** [comment]
Make sure you have linked the Masonry static library successfully if you didn't use cocoapods, besides, Masonry mainly expands some objective-c categories for UIKit/AppKit, so you had better check the following links out. Briefly, you should add flag -ObjC and -all_load to your project's "Other linker flags".

[Objective-C categories in static library](http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library)
[linking objective-c categories in a static library](http://stackoverflow.com/questions/6820778/linking-objective-c-categories-in-a-static-library)

Good luck!

**Comment by pickView** [comment]
i went meet the same question ,help

**Comment by burring55yali** [comment]
Build Settings ->Linking ->Other  Librarian Flags Add $(inherited)

**Comment by shanyimin** [comment]
![image](https://cloud.githubusercontent.com/assets/7760700/18123480/9ccdc97e-6fa0-11e6-9440-3a954e0ef8aa.png)

**Comment by applezqp** [comment]
@xingheng Thank you.

**Comment by BigShow1949** [comment]
If you want to use masonry without all those pesky 'mas_' prefixes. Add #define MAS_SHORTHAND to your prefix.pch before importing Masonry

**Comment by onezens** [comment]
> Build Settings ->Linking ->Other Librarian Flags Add $(inherited)

thanks ，work for me

**Comment by JakeTorres** [comment]
I meet the same question. and I had import the Masonry with cocoapods, add other linker flags and Header search paths, but still get error "[UILabel mas_makeConstraints:]: unrecognized selector sent to instance 0x7f8ff1423000"

#import "MainViewController.h"
#import  #"ProductViewController.h"
#import "Masonry.h"


@interface MainViewController ()

@end

@implementation MainViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.view.backgroundColor = [UIColor whiteColor];
    UIBarButtonItem *right = [[UIBarButtonItem alloc] initWithTitle:@"sub page" style:(UIBarButtonItemStylePlain) target:self action:@selector(pushPruductVc)];
    self.navigationItem.rightBarButtonItem = right;

    self.navigationItem.title = @"main home";

    [self setupSubViews];
}

- (void)setupSubViews {
    [self.view addSubview:self.productName];
    [self.productName mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(self.view);
        make.height.equalTo(@25);
    }];
}

- (void)pushPruductVc {
    ProductViewController *mainVc = [[ProductViewController alloc] init];
    [self.navigationController pushViewController:mainVc animated:YES];
}

- (void)updateProductScore:(NSString *)number {}

- (void)changeProducts:(NSString *)name{}

- (UILabel *)productName {
    if (!_productName) {
        _productName = [self produceLabelWithTitle:@"product" textColor:[UIColor darkTextColor] font:[UIFont systemFontOfSize:15] bgColor:[UIColor yellowColor]];
    }
    return _productName;
}

- (UILabel *)produceLabelWithTitle:(NSString *)title textColor:(UIColor *)color font:(UIFont *)font bgColor:(UIColor *)bgColor {
    UILabel *label = [[UILabel alloc] init];
    label.text = title;
    label.textColor = color;
    label.font = font;
    label.backgroundColor = bgColor;
    return label;
}


021-12-10 16:07:00.858685+0800 CZHInherited[17978:132206] -[UILabel mas_makeConstraints:]: unrecognized selector sent to instance 0x7f8ff1423000
