### ISSUE TITLE
Can't form weak reference to a NSTextView

### ISSUE THREAD

**Issue by kasperkronborg** [Masonry/Masonry#19]
As mentioned in Apples [Transitioning to ARC Release Notes](https://developer.apple.com/library/ios/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW17) you can't create a weak reference to instances of class NSTextView. Meaning the app will crash if you are trying to call mas_makeConstraints: on a NSTextView.

Since i love using Masonry, I would love to see this being implemented so that I can use it for my Mac OS X projects as well.

Do you see this feature being implemented or will you go on not supporting this?

Thanks!

**Comment by akinsey** [comment]
+1

**Comment by hamin** [comment]
@cloudkite @kasperkronborg on mac you can't have weak references to NSTextView. Solution use assign http://zpasternack.org/some-objects-dont-support-weak-references/

**Comment by hamin** [comment]
@cloudkite @kasperkronborg on mac you can't use weak references to NSTextView. Use assign instead. Here's a reference http://zpasternack.org/some-objects-dont-support-weak-references/

**Comment by jhoughjr** [comment]
I think if Masonry did a check for isMemberOfClass and then used an assigned property that would be a solution, From the front end side though you either must use strong, or ensure it's added as a subview  before assigning it, since it would otherwise not be retained.

**Comment by kasperkronborg** [comment]
@hamin That's what initially caused the issue. If you read my first post, I write that it is because you can't create weak references to NSTextView that Masonry crashes the app :)
