### ISSUE TITLE
Issues with multiple views inside a UIScrollView

### ISSUE THREAD

**Issue by lluisgerard** [Masonry/Masonry#25]
Hi there,

First of all, I want to say that this library is really awesome and is one of the reasons that I'm using autolayout right now. Been using it for a new project and everything is working like a charm, really appreciate it.

But, I'm trying to use it on a ScrollView and I'm having a lot of trouble. I tried to solve this in multiple ways and different approaches and I'm not having any success at all. The more I try the less I feel I understand how Autolayout and Masonry works. Maybe that's the problem, not Masonry but the way Autolayout works in ScrollViews.

The main issue I have is that the scrollView only scrolls horizontally and not vertically, it's stuck.

Found this issue https://github.com/cloudkite/Masonry/issues/12 and tried to always set the width of my subviews. I even copied exactly what he did there, but then I created like 50 views in the same scrollView and it doesn't scroll.

Been reading this https://developer.apple.com/library/ios/technotes/tn2154/_index.html but in this case, they use only one big view, and not multiple ones.

At this point, after so many hours trying, I think that I'd better see an example and start again than try to fix my own one so I created a new ViewController and added this code to the init:

```
    self.scrollView = [[UIScrollView alloc] initWithFrame:CGRectZero];
    _scrollView.backgroundColor = [UIColor grayColor];
    [self.view addSubview:_scrollView];

    [_scrollView makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];

    NSNumber* height = [NSNumber numberWithInt:350];

    UIView *view1 = [[UIView alloc] initWithFrame:CGRectZero];
    view1.backgroundColor = [UIColor blueColor];
    [_scrollView addSubview:view1];


    UIView *view2 = [[UIView alloc] initWithFrame:CGRectZero];
    view2.backgroundColor = [UIColor greenColor];
    [_scrollView addSubview:view2];


    UIView *view3 = [[UIView alloc] initWithFrame:CGRectZero];
    view3.backgroundColor = [UIColor redColor];
    [_scrollView addSubview:view3];

    [view1 makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(@0);
        make.left.equalTo(@0);
        make.width.equalTo(_scrollView.width);
        make.height.equalTo(height);
    }];

    [view2 makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(view1.mas_bottom);
        make.left.equalTo(@0);
        make.width.equalTo(_scrollView.width);
        make.height.equalTo(height);
    }];

    [view3 makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(view2.mas_bottom);
        make.left.equalTo(@0);
        make.width.equalTo(_scrollView.width);
        make.height.equalTo(height);
    }];
```

This code adds the first view and the next two correctly, one using the bottom as a top reference, but the UISCrollView **is not scrolling at all**. I also tried to add everything inside a UIView. I even tried to get the last object Y position, but I get a very high number that doesn't make sense. 

Should I have to set the contentSize of the scrollView ? but that's why I wanted the Y position for, I'm feeling that this is the wrong direction.

At this point I hope that somebody can help me, I will really appreciate it, and even better, seeing some **example**. I think I'm missing something here.

Thanks in advance :)

**Comment by Kastr** [comment]
As I couldn't find this solution anywhere else but here, in case someone needs it...

I didn't have to add the footer view.
Just set the bottom constraint of the last view in the scrollview and it works fine.
In the example code above, the last useful view would be the view3.
In Swift:

```
view3.snp.makeConstraints { make in
        make.top.equalTo(view2.snp.bottom)
        make.left.equalToSuperview()
        make.right.equalToSuperview()
        make.bottom.equalTo(scrollView.snp.bottom).offset(-20)
}
```
