### ISSUE TITLE
Support for UILayoutSupports (topLayoutGuide & bottomLayoutGuide)

### ISSUE THREAD

**Issue by raylillywhite** [Masonry/Masonry#27]
Support for building constraints with topLayoutGuide and bottomLayoutGuide would be great. From what I understand, using the length property of the guide to build the constraint would require us to also monitor for status bar frame changes, and reconfigure our constraints.

This looks like it would be difficult to support without a big refactor, but if you have ideas for how you'd like this implemented, I'd be happy to work on it.

**Comment by dlahyani** [comment]
With iOS9 they replaced the layout guides from <code>_UILayoutGuide</code> (internal class which is a subclass of <code>UIView</code>) to <code>UILayoutGuide</code> which is not a <code>UIView</code> anymore. Do you guys intend to support the new layout guides in the Masonry?

**Comment by hjue** [comment]
The length of topLayoutGuide is difference between  viewDidLoad  and viewWillAppear
