### ISSUE TITLE
获取frame 问题(自己代码问题 请关闭)

### ISSUE THREAD

**Issue by czboosj** [Masonry/Masonry#512]
### New Issue Checklist

* [x] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. iOS
 Platform Version        | e.g. 11.3
 Masonry Version         | e.g. 1.1.0
 Integration Method      | e.g. cocoapods
 

### Issue Description
iOS 11.3  执行 " self.topView.layoutIfNeeded();"   没有获得正确的frame , frame.x , frame.y 错误

**Comment by faimin** [comment]
It,s not Masonry's bug

**Comment by AAChartModel** [comment]
关闭 issue 不是自己就可以操作吗?干嘛要劳烦作者?!!!
