### ISSUE TITLE
fistBaseline/lastBaseline.project Deployment target >=8.0 crash

### ISSUE THREAD

**Issue by chen0807130004** [Masonry/Masonry#514]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 8.0
 Masonry Version         | e.g. 1.1.0
 Integration Method      | e.g. cocoapods
 

### Issue Description

⚠️ my project deployment target >=8.0, but when I used  fistBaseline and lastBaseline will crash like -[MASConstraintMaker lastBaseline]: unrecognized selector sent to instance 0x608000222d60 . ⚠️ 

so I need go to pods targets choose  Masonry ,change  ios Deployment Target from 6.0 to 8.0.  it can be work. but when I pod install. the set value back to 6.0.  how to fixed it just one time

**Comment by faimin** [comment]
try to add the follow code to `podfile`.

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Masonry'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
```

**Comment by chen0807130004** [comment]
@faimin It  work for me ，thanks
