### ISSUE TITLE
两个view水平排列时怎么让左view的左边距等于右view的右边距

### ISSUE THREAD

**Issue by jiutianhuanpei** [Masonry/Masonry#527]
### Issue Description

![](https://ws3.sinaimg.cn/large/006tKfTcgy1ftezre6cr8j31kw23vb29.jpg)

这是我的需求：

水平排列的两个视图，v1 及 v2

v1的宽为50，v2的宽为100，它们的间距为5，我需要v1的左边距x 等于 v2的右边距y

可能在项目之中 v2的宽可能需要自适应，所以不能用计算的方法先算出 x 的值 。

**Comment by Daniate** [comment]
You should add placeholder views at the position of x & y

**Comment by jiutianhuanpei** [comment]
@Daniate Can you write a sample code ？

**Comment by Daniate** [comment]
@jiutianhuanpei Are you a beginner?

### Plan 1
<img width="668" alt="2018-08-29 7 09 14" src="https://user-images.githubusercontent.com/1210634/44755899-a6e17580-ab5a-11e8-9803-8981551cc93e.png">

Wrap v1&v2，you should add some constraints. I think you can.

### Plan 2
<img width="675" alt="2018-08-29 7 09 19" src="https://user-images.githubusercontent.com/1210634/44755911-b06add80-ab5a-11e8-88fc-c4e9805bb4fe.png">

**I think you can understand these figures.**

**Comment by jiutianhuanpei** [comment]
Thanks ，I see what you mean

**Comment by Wenjie-Qin** [comment]
只有这两种方法吗？这两种方法都要多创建出来视图控件作为辅助，没有其他更好的方法吗？

**Comment by Daniate** [comment]
加入辅助视图，是苹果官方给的解决方案，在AutoLayout早期相关的文档里，有相关描述，不过现在无法找到相关文档了，但苹果给了示例项目[Auto-Layout-Cookbook](https://developer.apple.com/sample-code/xcode/downloads/Auto-Layout-Cookbook.zip)，里面有个`EqualWhiteSpace`的示例，用的就是辅助视图，苹果把它们称作`dummy views`
