### ISSUE TITLE
19808 build warnings with new Xcode (11.0 (11A420a))

### ISSUE THREAD

**Issue by leechoohyoung** [Masonry/Masonry#566]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ v ] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ v ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 12.2 (16E227)
 Masonry Version         | 1.1.0
 Integration Method      | cocoapods
 

### Issue Description

When I build my project with new Xcode (11.0 (11A420a)), 
generate too many build warnings like below...(real device and simulator)

ld: warning: instance method 'remakeConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'updateConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'makeConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'attribute' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'safeAreaLayoutGuideRight' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'safeAreaLayoutGuideLeft' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'safeAreaLayoutGuideBottom' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'safeAreaLayoutGuideTop' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'centerYWithinMargins' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'centerXWithinMargins' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'trailingMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'leadingMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'bottomMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'topMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'rightMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'leftMargin' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'lastBaseline' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'firstBaseline' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'baseline' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'centerY' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'centerX' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'height' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'width' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'trailing' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'leading' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'right' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'bottom' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'left' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'top' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'remakeConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'updateConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'makeConstraints:' in category from /.../MySomeObject.o conflicts with same method from another category
ld: warning: instance method 'attribute' in category from /.../MySomeObject.o conflicts with same method from another category

...19808 warnings!!!

Please check this out

**Comment by ZombieMK** [comment]
I have the same problem

**Comment by leechoohyoung** [comment]
ok, so far, I found a little hint.
Changing build type of workspace(new build system to legacy build system), xcode reported 230 build warnings.

**Comment by ZombieMK** [comment]
Yes, same for me... Not a fix per se, but a start :)

**Comment by frank-du** [comment]
i have the same problem with 2w+ warnings😁

**Comment by meloanyang** [comment]
I have the same problem , too;

**Comment by babucha** [comment]
Same here

**Comment by terence612** [comment]
Same here

**Comment by Jimmygio** [comment]
Same here +1

**Comment by Jimmygio** [comment]
I find a solution.

The problem is happen in "View+MASShorthandAdditions.h" and "NSArray+MASShorthandAdditions.h" exist "@implementation" code.

So I create "View+MASShorthandAdditions.m" and "NSArray+MASShorthandAdditions.m" by myself, and move "@implementation" code to the two .m files, then the compare warning is down!

**Comment by frank-du** [comment]
> I find a solution.
> 
> The problem is happen in "View+MASShorthandAdditions.h" and "NSArray+MASShorthandAdditions.h" exist "@implementation" code.
> 
> So I create "View+MASShorthandAdditions.m" and "NSArray+MASShorthandAdditions.m" by myself, and move "@implementation" code to the two .m files, then the compare warning is down!

Worked.

**Comment by warpling** [comment]
Thank you @Jimmygio! Made [a branch with the fixes](https://github.com/warpling/Masonry) for anyone else still moving off Masonry.

**Comment by songwentong** [comment]
me too

**Comment by songwentong** [comment]
@warpling  thank you !

**Comment by vbonluk** [comment]
same problem

**Comment by JackyGohSG** [comment]
> o .m

Only the @implementation code or all the lines below it as well? Quite new to Xcode.

**Comment by JackyGohSG** [comment]
> > o .m
> 
> Only the @implementation code or all the lines below it as well? Quite new to Xcode.

Nvm just saw warpling commit and understand it better. Cheers

**Comment by zhenghongfeng** [comment]
> > I find a solution.
> > The problem is happen in "View+MASShorthandAdditions.h" and "NSArray+MASShorthandAdditions.h" exist "@implementation" code.
> > So I create "View+MASShorthandAdditions.m" and "NSArray+MASShorthandAdditions.m" by myself, and move "@implementation" code to the two .m files, then the compare warning is down!
> 
> Worked.

thank you very much!
