### ISSUE TITLE
苹果新政策要求三方库添加隐私清单PrivacyManifest，能否支持一下？

### ISSUE THREAD

**Issue by FanningHau** [Masonry/Masonry#608]
以下是苹果新政链接：
[https://developer.apple.com/documentation/bundleresources/privacy_manifest_files](url)

**Comment by zcsyIos** [comment]
no suppport ，Because it is not on the enforcement list

**Comment by zcsyIos** [comment]
If you have any questions about the PrivacyInfo.xcprivacy, please refer to here ：https://www.jianshu.com/p/9a9ec34395e2

**Comment by fanninghau** [comment]
不知道这个文章从哪里得到的只有framework加隐私清单，apple要求的是三方库都要添加，目前稍微大点儿的三方库即使是源码的都添加了

**Comment by MyNameZhangXinMiao** [comment]
@cloudkite 
@robertjpayne 
@nickynick 
@CraigSiemens 
@kovpas 
@iwill 
@danielrhammond 
@rastersize 
@pingyourid 
@ahti 
@kouky 
@dlo 
@whalec 
@vascoorey
