### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by behappyenjoylife** [Masonry/Masonry#76]
I am applying the constrains over the subview that is tableview of viewcontroller HelpDetailVC and i found that dealloc method is not called if we keep constrain.

__weak UIView *superview = self.view;
    [self.tableview mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(superview);
    }];

So if now i comment the make.edges part it start calling dealloc method.
__weak UIView *superview = self.view;
    [self.tableview mas_makeConstraints:^(MASConstraintMaker *make) {
        //make.edges.equalTo(superview);
    }];

So can you please verify this it is an issue?

**Comment by aelam** [comment]
@prakashdonga8  what's the problem?
