### ISSUE TITLE
Incorporating top layout guide

### ISSUE THREAD

**Issue by akashivskyy** [Masonry/Masonry#9]
I am using a transparent `UINavigationBar` and `UITextField`. I want it to be 20px under the navigation bar, so I'm using the following commands:

``` objc
[self.emailTextField mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.equalTo((self.view).mas_top).with.offset(20);
}];
```

However, my text field appears beneath the navigation bar, 20px from the top of the **screen**.

**-- iOS 7 SPOILER ALERT --**

In iOS 7 there is a `topLayoutGuide` property on `UIViewController`. How can I incorporate it using Masonry, so my text field appears under the navigation bar (84px from the top of the screen) both in iOS 7 with transparent navigation bar and in iOS 6?

I know that it can be done using `NSLayoutConstraints`. Taken from the documentation:

``` objc
id topGuide = myViewController.topLayoutGuide;
// "button" is a UIButton object specified elsewhere
[myViewController.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:[topGuide]-20-[button]"]];
```

**Comment by Pratik-Sodha** [comment]
topLayoutGuide deprecated in iOS 11, Use view.safeAreaLayoutGuide.topAnchor instead of topLayoutGuide.bottomAnchor_ 

```
        txtLink.snp.makeConstraints { (make) in
            make.top.equalTo(self.view.safeAreaLayoutGuide).inset(20)
        }
```
